const EXPRESS_SERVER_TOKEN = Symbol("EXPRESS_SERVER_TOKEN");
const DEFAULT_LOGGER_TOKEN = Symbol("DEFAULT_LOGGER_TOKEN");
const POSTGRES_TOKEN = Symbol("POSTGRES_TOKEN");
const DB_CONNECTION_TOKEN = Symbol("DB_CONNECTION_TOKEN");
const REDIS_TOKEN = Symbol("REDIS_TOKEN");
const WINSTON_LOGGER_TOKEN = Symbol("WINSTON_TOKEN");

const TOKENS = {
	EXPRESS_SERVER_TOKEN,
	DEFAULT_LOGGER_TOKEN,
	POSTGRES_TOKEN,
	DB_CONNECTION_TOKEN,
	REDIS_TOKEN,
	WINSTON_LOGGER_TOKEN,
};

export default TOKENS;
