const DB_CONNECTION_TOKEN = Symbol("DB_CONNECTION_TOKEN");
const REDIS_TOKEN = Symbol("REDIS_TOKEN");
const WINSTON_LOGGER_TOKEN = Symbol("WINSTON_TOKEN");
const USER_REPOSITORY_TOKEN = Symbol("USER_REPOSITORY_TOKEN");
const USER_SERICE_TOKEN = Symbol("USER_SERICE_TOKEN");
const HANDLER_SERVICE_TOKEN = Symbol("HANDLER_SERVICE_TOKEN");
const CRYPTO_SERVICE_TOKEN = Symbol("CRYPTO_SERVICE_TOKEN");
const MAIL_SENDING_SERVICE = Symbol("MAIL_SENDING_SERVICE");

const TOKENS = {
	DB_CONNECTION_TOKEN,
	REDIS_TOKEN,
	WINSTON_LOGGER_TOKEN,
	USER_REPOSITORY_TOKEN,
	USER_SERICE_TOKEN,
	HANDLER_SERVICE_TOKEN,
	CRYPTO_SERVICE_TOKEN,
	MAIL_SENDING_SERVICE,
};

export default TOKENS;
